name: Symfony

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-unitys:
    runs-on: ubuntu-latest
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Update Dependencies
      run: composer update
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit tests/Unit --testdox

  symfony-functionnel:
      needs: symfony-unitys
      runs-on: ubuntu-latest
      steps:
        #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
        # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
        # uses: shivammathur/setup-php@v2
        - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
          with:
            php-version: '8.0'
        - uses: actions/checkout@v3
        - name: Update Dependencies
          run: composer update
        - name: Execute tests (Unit and Feature tests) via PHPUnit
          run: vendor/bin/phpunit tests/Func/*